<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\WhitePayment.Application\WhitePayment.Application.csproj" />
    <ProjectReference Include="..\WhitePayment.Domain\WhitePayment.Domain.csproj" />
  </ItemGroup>

</Project>
